processed_data_path: 'data/processed/baseline.pickle'
feature_path: 'data/features/baseline.pickle'
keep_columns:
  - 'item_id'
  - 'deal_probability'
  - 'is_train'
  - 'kfold'

raw_features:
  save_path: 'data/features/raw_features/features.pickle'
  columns:
    - 'price'
    - 'item_seq_number'
    - 'image_class'
    - 'user_type'
    - 'region_id'
    - 'category_id_1'
    - 'category_id_2'

concat_group_aggregation:
  save_dir: 'data/features/group_aggregation'
  configs:
    -
      group_keys: 'user_id'
      target: 'item_id'
      agg: 'count'
      fillna: 0
      filter_train: False
      feature_name: 'nunique_iid_by_uid'
    -
      group_keys: 'user_id'
      target: 'price'
      agg: 'mean'
      fillna: 0
      filter_train: False
      feature_name: 'avg_price_by_uid'
    -
      group_keys: 'user_id'
      target: 'price'
      agg: 'min'
      fillna: 0
      filter_train: False
      feature_name: 'min_price_by_uid'
    -
      group_keys: 'user_id'
      target: 'price'
      agg: 'max'
      fillna: 0
      filter_train: False
      feature_name: 'max_price_by_uid'

concat_diff_features:
  save_dir: 'data/features/diff_features'
  configs:
    -
      left_feature: 'price'
      right_feature: 'avg_price_by_uid'
      feature_name: 'diff_price-avg_price_by_uid'

concat_text_basic_aggregation:
  save_dir: 'data/features/text_basic_aggregation'
  configs:
    -
      text_column: 'title'
      feature_name: 'title'
    -
      text_column: 'description'
      feature_name: 'description'

concat_tfidf_aggregation:
  save_dir: 'data/features/tfidf_aggregation'
  configs:
    -
      tfidf_params:
        analyzer: 'word'
        smooth_idf: True
      text_column: 'title'
      feature_name: 'tfidf-agg_title'
    -
      tfidf_params:
        analyzer: 'word'
        smooth_idf: False
      text_column: 'title'
      feature_name: 'count-agg_title'

concat_tfidf_svd:
  save_dir: 'data/features/tfidf_svd'
  configs:
    -
      tfidf_params:
        analyzer: 'word'
        smooth_idf: True
      svd_params:
        n_components: 5
        random_state: 0
      text_column: 'title'
      feature_name: 'tfidf-svd_title'
    -
      tfidf_params:
        analyzer: 'word'
        smooth_idf: False
      svd_params:
        n_components: 5
        random_state: 0
      text_column: 'title'
      feature_name: 'count-svd_title'